/* Generated by tools/sync_portfolio_images.py. Do not edit by hand. */
window.folderMedia = {
  "generatedAt": "2026-09-21T21:59:39+00:00",
  "projects": {
    "birch-gold-conversion": {
      "folder": "birch-gold-digital-marketing",
      "cover": "content/projects/birch-gold-digital-marketing/images/featured/Screenshot-2026-09-14-at-9.52.21-AM.png?v=1789404747330000043",
      "gallery": [
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/01-Screenshot-2026-09-14-at-9.54.08-AM.png?v=1789404854559999943",
          "alt": "2026 Birch Gold information kit front and back cover",
          "layout": "landscape",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/02-Screenshot-2026-09-14-at-9.58.png?v=1789656825952586869",
          "alt": "2026 Birch Gold information kit shown in print, tablet, and mobile formats",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/03-2025-birch-gold-information-kit-cover.webp?v=1789661134445489638",
          "alt": "2025 birch gold information kit cover",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/03-end-of-the-dollar-empire-book-cover.webp?v=1789660744678929389",
          "alt": "End of the dollar empire book cover",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/04-Screenshot-2025-10-21-at-1.59.07-PM.png?v=1761080353490000010",
          "alt": "Screenshot 2025 10 21 at 1.59.07 PM",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/04a-Screenshot-2025-10-21-at-1.53.50-PM.png?v=1761080035960000038",
          "alt": "04a Screenshot 2025 10 21 at 1.53.50 PM",
          "layout": "landscape",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/05-two-free-gifts-campaign-graphic.webp?v=1788658795288122700",
          "alt": "Two free gifts campaign graphic",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/06-Screenshot-2025-10-21-at-2.03.22-PM.png?v=1761080608250000000",
          "alt": "Screenshot 2025 10 21 at 2.03.22 PM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/07-Screenshot-2025-09-09-at-9.48.34-AM.png?v=1789744702588696028",
          "alt": "Screenshot 2025 09 09 at 9.48.34 AM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/08-Screenshot-2025-09-09-at-9.48.56-AM.png?v=1789744773252480690",
          "alt": "Screenshot 2025 09 09 at 9.48.56 AM",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/09-Screenshot-2025-09-09-at-9.49.17-AM.png?v=1789744810089539431",
          "alt": "Screenshot 2025 09 09 at 9.49.17 AM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/10-Screenshot-2025-09-09-at-9.49.28-AM.png?v=1789744848266742198",
          "alt": "Screenshot 2025 09 09 at 9.49.28 AM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2025-09-09-at-9.50.06-AM.png?v=1789661187782098065",
          "alt": "Screenshot 2025 09 09 at 9.50.06 AM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2025-10-21-at-2.01.40-PM.png?v=1761080506389999986",
          "alt": "Screenshot 2025 10 21 at 2.01.40 PM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2025-10-21-at-2.04.45-PM.png?v=1761080691480000019",
          "alt": "Screenshot 2025 10 21 at 2.04.45 PM",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2026-09-14-at-9.57.03-AM.png?v=1789405029190000057",
          "alt": "Birch Gold silver referral print design",
          "layout": "landscape",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2026-09-14-at-9.59.14-AM.png?v=1789405160220000029",
          "alt": "Learn and Earn event graphic on a dark background",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2026-09-14-at-9.59.25-AM.png?v=1789405171019999981",
          "alt": "Learn and Earn event graphic with course preview",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2026-09-14-at-9.59.38-AM.png?v=1789405183789999962",
          "alt": "Learn and Earn last-chance event graphic",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/graphic-design/Screenshot-2026-09-14-at-9.59.52-AM.png?v=1789405198029999971",
          "alt": "Learn and Earn event graphic on a light background",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/motion-video/01-how-to-open-a-gold-ira-video-thumbnail.png?v=1787526300989525437",
          "alt": "How to open a gold ira video thumbnail",
          "layout": "wide",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/birch-gold-digital-marketing/images/motion-video/02-why-a-gold-ira-video-thumbnail.png?v=1787526300991941452",
          "alt": "Why a gold ira video thumbnail",
          "layout": "wide",
          "section": "Motion & video"
        }
      ]
    },
    "france-luxe-art-direction": {
      "folder": "france-luxe-art-direction",
      "cover": "content/projects/france-luxe-art-direction/images/featured/01-tropical-editorial-li7591-black-03.jpg?v=1787526301445314288",
      "gallery": [
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/01-crystal-accessory-colorful-portrait.jpg?v=1787526301484922051",
          "alt": "Crystal accessory colorful portrait",
          "layout": "portrait",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/02-leopard-accessory-beach-styling.jpg?v=1787526301515715480",
          "alt": "Leopard accessory beach styling",
          "layout": "portrait",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/03-pastel-studio-accessories-portrait.jpg?v=1787526301439285874",
          "alt": "Pastel studio accessories portrait",
          "layout": "portrait",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/04-spring-floral-accessories-portrait.jpg?v=1787526301427492380",
          "alt": "Spring floral accessories portrait",
          "layout": "portrait",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/05-sculptural-gold-hair-accessory-detail.jpg?v=1787526301466748595",
          "alt": "Sculptural gold hair accessory detail",
          "layout": "landscape",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/06-rose-gold-outdoor-portrait.jpg?v=1787526301452412963",
          "alt": "Rose gold outdoor portrait",
          "layout": "landscape",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/07-beach-editorial-banner.jpg?v=1787526301449072957",
          "alt": "Beach editorial banner",
          "layout": "wide",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/08-purple-headband-studio.jpg?v=1787526301480113387",
          "alt": "Purple headband studio",
          "layout": "landscape",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/09-blue-headscarf-against-patterned-tiles.jpg?v=1787526301371943116",
          "alt": "Blue headscarf against patterned tiles",
          "layout": "landscape",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/12-pearl-accessory-studio-detail.jpg?v=1787526301476496339",
          "alt": "Pearl accessory studio detail",
          "layout": "landscape",
          "section": "Art direction"
        },
        {
          "src": "content/projects/france-luxe-art-direction/images/art-direction/13-autumn-tailoring-and-headband-portrait.jpg?v=1787526301491722584",
          "alt": "Autumn tailoring and headband portrait",
          "layout": "landscape",
          "section": "Art direction"
        }
      ]
    },
    "france-luxe-campaigns": {
      "folder": "france-luxe-campaigns",
      "cover": "content/projects/france-luxe-campaigns/images/featured/01-spring-is-in-the-air-homepage-campaign.jpg?v=1787526301527625799",
      "gallery": [
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/01-spring-accessories-social-campaign.jpg?v=1787526301601862788",
          "alt": "Spring accessories social campaign",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/02-spring-campaign-cozy-scrunchies-social-tile.jpg?v=1787526301569719791",
          "alt": "Spring campaign cozy scrunchies social tile",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/03-classics-campaign-barrette.jpg?v=1787526301600692153",
          "alt": "Classics campaign barrette",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/04-classics-campaign-jaw-clips.jpg?v=1787526301596355796",
          "alt": "Classics campaign jaw clips",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/05-grab-and-go-colorful-ponytail-holders.jpg?v=1787526301622816920",
          "alt": "Grab and go colorful ponytail holders",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/06-chic-chignon-email.jpg?v=1787526301629550695",
          "alt": "Chic chignon email",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/07-click-clack-email.jpg?v=1787526301649260998",
          "alt": "Click clack email",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/08-crystal-accessories-email.jpg?v=1787526301639548898",
          "alt": "Crystal accessories email",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/09-holiday-barrettes-campaign.jpg?v=1787526301641263247",
          "alt": "Holiday barrettes campaign",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/10-tube-jaw-clip-email.jpg?v=1787526301668875575",
          "alt": "Tube jaw clip email",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/11-plush-pony-campaign.jpg?v=1787526301581143737",
          "alt": "Plush pony campaign",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/12-sale-on-sale-classics.jpg?v=1787526301614645600",
          "alt": "Sale on sale classics",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/13-spring-sale-combs.jpg?v=1787526301617159128",
          "alt": "Spring sale combs",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/14-spring-sale-headbands.jpg?v=1787526301572771072",
          "alt": "Spring sale headbands",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/15-spring-sale-scrunchies.jpg?v=1787526301576248527",
          "alt": "Spring sale scrunchies",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/graphic-design/16-spring-sale-announcement.jpg?v=1787526301579787612",
          "alt": "Spring sale announcement",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/digital-web/01-spring-collection-email.jpg?v=1787526301663692594",
          "alt": "Spring collection email",
          "layout": "portrait",
          "section": "Digital & web"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/digital-web/02-sale-on-sale-homepage-banner.jpg?v=1787526301536750317",
          "alt": "Sale on sale homepage banner",
          "layout": "wide",
          "section": "Digital & web"
        },
        {
          "src": "content/projects/france-luxe-campaigns/images/digital-web/03-sale-on-sale-matching-social-creative.jpg?v=1787526301604696751",
          "alt": "Sale on sale matching social creative",
          "layout": "portrait",
          "section": "Digital & web"
        }
      ]
    },
    "somatic-living-creative-system": {
      "folder": "somatic-living-creative-system",
      "cover": "content/projects/somatic-living-creative-system/images/featured/Somatic LIving-Eposide 6 thumbnail-v2.jpg?v=1789332854309555883",
      "gallery": [
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/01-strength-in-alignment-flower.webp?v=1788668592804650648",
          "alt": "Strength in alignment flower",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/02-strength-in-alignment-movement.webp?v=1788668592945578891",
          "alt": "Strength in alignment movement",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/03-body-awareness-sculptural-form.webp?v=1788668593251808044",
          "alt": "Body awareness sculptural form",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/04-body-awareness-nature.webp?v=1788668593516161009",
          "alt": "Body awareness nature",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/05-layers-of-the-body-collage.webp?v=1788668593746714981",
          "alt": "Layers of the body collage",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/06-layers-of-the-body-botanical.webp?v=1788668593923724516",
          "alt": "Layers of the body botanical",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/07-comfortable-with-silence-opening.webp?v=1788668594107546825",
          "alt": "Comfortable with silence opening",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/08-comfortable-with-silence-reflection.webp?v=1788668594397986173",
          "alt": "Comfortable with silence reflection",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/graphic-design/video-thumbnail-body-practice.jpg?v=1788277108141491105",
          "alt": "Video thumbnail body practice",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/digital-web/05-layers-of-the-body-collage.webp?v=1788668593746714981",
          "alt": "Layers of the body collage",
          "layout": "portrait",
          "section": "Digital & web"
        },
        {
          "src": "content/projects/somatic-living-creative-system/images/motion-video/practice-video-still.png?v=1788277108144082221",
          "alt": "Practice video still",
          "layout": "wide",
          "section": "Motion & video"
        }
      ]
    },
    "zumiez-ecommerce": {
      "folder": "zumiez-ecommerce-design",
      "cover": "content/projects/zumiez-ecommerce-design/images/featured/01-spring-looks-seasonal-ecommerce-campaign.jpg?v=1787526301155803800",
      "gallery": [
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/01-rick-and-morty-primitive-skateboard-campaign.jpg?v=1787526301113278270",
          "alt": "Rick and morty primitive skateboard campaign",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/02-dragon-ball-z-primitive-exclusive-campaign.jpg?v=1787526301152646542",
          "alt": "Dragon ball z primitive exclusive campaign",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/03-new-balance-footwear-campaign.jpg?v=1787526301111308217",
          "alt": "New balance footwear campaign",
          "layout": "square",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/04-vans-david-bowie-animated-campaign.webp?v=1788658826464421244",
          "alt": "Vans david bowie animated campaign",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/05-nixon-watch-campaign.jpg?v=1787526301201345682",
          "alt": "Nixon watch campaign",
          "layout": "portrait",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/graphic-design/06-adidas-footwear-banner.jpg?v=1787526301114074826",
          "alt": "Adidas footwear banner",
          "layout": "wide",
          "section": "Graphic design"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/07-ripndip-footwear-campaign.gif?v=1787526301157668591",
          "alt": "Ripndip footwear campaign",
          "layout": "portrait",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/08-zion-skate-campaign.gif?v=1787526301165813327",
          "alt": "Zion skate campaign",
          "layout": "square",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/09-rick-and-morty-launch.gif?v=1787526301109233856",
          "alt": "Rick and morty launch",
          "layout": "portrait",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/10-dragon-ball-z-apparel.gif?v=1787526301216358423",
          "alt": "Dragon ball z apparel",
          "layout": "portrait",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/11-king-ice-spongebob-campaign.gif?v=1787526301188625693",
          "alt": "King ice spongebob campaign",
          "layout": "portrait",
          "section": "Motion & video"
        },
        {
          "src": "content/projects/zumiez-ecommerce-design/images/motion-video/12-odd-future-swimwear.gif?v=1787526301121465802",
          "alt": "Odd future swimwear",
          "layout": "portrait",
          "section": "Motion & video"
        }
      ]
    }
  }
};
